spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: moliniao-config-dev
---
spring:
  profiles: test
  application:
    name: moliniao-config-test
---
spring:
  profiles: prod
  application:
    name: moliniao-config-prod-limingzhou

# 请保存为UTF-8格式
