#spring:
#  profiles:
#    active:
#    - dev
#---     #分割符
#server:
#  port: 8201
#
#spring:
#  profiles: dev    #开发环境
#  application:
#    name: moliniao-springcloud-config-client-dev
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-dev.com:7001/eureka/
#
#---
#
#server:
#  port: 8202
#
#spring:
#  profiles: test    #测试环境
#  application:
#    name: moliniao-springcloud-config-client-test
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-test.com:7001/eureka/
