server:
  port: 9527

spring:
  application:
    name: moliniao-zuul-gateway

#before http://zuul.com:9527/moliniao-provider-ribbon/getOrder?studentId=2

zuul:
  prefix: /moliniao                  #设置统一公共前缀
  ignored-services: moliniao-provider-ribbon #隐藏真实微服务名称，设置一个服务名称隐藏
  #ignored-services: "*"             #设置多个服务名称隐藏
  routes:
    route.serviceId: moliniao-provider-ribbon
    route.path: /route/**


#after http://zuul.com:9527/moliniao-provider-ribbon/getOrder?studentId=2


eureka:
  instance:
#    instance-id: moliniao-zuul-gateway
    instance-id: zuul.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaone.com:7001/eureka/,http://eurekatwo.com:7002/eureka/,http://eurekathree.com:7003/eureka/

info:
  app.name: moliniao-spring-cloud
  company.name: www.moliniao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
