server:
  port: 9527

spring:
  application:
    name: moliniao-zuul-gateway


#zuul:
#  prefix: /atguigu                  #设置统一公共前缀
#  ignored-services: microservice-springcloud-provider
#  #ignored-services: "*"     #设置多个服务名称隐藏
#  routes:
#    mydept.serviceId: microservice-springcloud-provider
#    mydept.path: /mydept/**

eureka:
  instance:
    instance-id: moliniao-zuul-gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaone.com:7001/eureka/,http://eurekatwo.com:7002/eureka/,http://eurekathree.com:7003/eureka/

info:
  app.name: moliniao-spring-cloud
  company.name: www.moliniao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
